#!/usr/bin/env bash
wget https://medium.com/@AtrinAssa/the-dangerous-and-colorful-lie-in-your-visual-identity-document-db3c3ad27db5
wget https://medium.com/@addyosmani/javascript-application-architecture-on-the-road-to-2015-d8125811101b
wget https://medium.com/@b_k/https-the-end-of-an-era-c106acded474
wget https://medium.com/@bn2b/making-web-pages-go-fast-8fb8e86ed0ff
wget https://medium.com/@ded/why-im-staying-with-node-e6fd3be62e34
wget https://medium.com/@denizozger/finding-the-right-node-js-websocket-implementation-b63bfca0539
wget https://medium.com/@dte/understanding-css-selector-specificity-a02238a02a59
wget https://medium.com/@edwardbenson/how-i-hacked-amazon-s-5-wifi-button-to-track-baby-data-794214b0bdd8
wget https://medium.com/@housecor/react-s-jsx-the-other-side-of-the-coin-2ace7ab62b98
wget https://medium.com/@jasonfried/give-it-five-minutes-b8115d6f2361
wget https://medium.com/@jdaudier/how-to-create-and-publish-your-first-node-js-module-444e7585b738
wget https://medium.com/@leeb/why-invest-in-tools-3240ce289930
wget https://medium.com/@mach/the-secret-of-san-francisco-fonts-4b5295d9a745
wget https://medium.com/@nodesource/the-state-of-node-in-the-enterprise-e513fbc0bdc
wget https://medium.com/@padlet/an-honest-guide-to-the-san-francisco-startup-life-6df13d23689
wget https://medium.com/@tjholowaychuk/farewell-node-js-4ba9e7f3e52b
wget https://medium.com/@tschundeee/express-vs-flask-vs-go-acc0879c2122
wget https://medium.com/@typographias/learning-to-make-a-font-the-hard-way-5c5c7045e92f
wget https://medium.com/@victordoss/building-backbone-apps-using-flux-f656fd8a873a
wget https://medium.com/backchannel/how-companies-can-avoid-the-innovator-s-dilemma-3f980ae533a7
wget https://medium.com/backchannel/i-ve-spent-a-lifetime-building-a-mighty-network-here-are-my-secrets-8590d893d30c
wget https://medium.com/conquering-corporate-america/10-tricks-to-appear-smart-during-meetings-27b489a39d1a
wget https://medium.com/design-and-innovation/design-pretty-b7ab0158454c
wget https://medium.com/facebook-design/how-not-to-make-your-engineer-s-life-completely-terrible-292a6d5d134c
wget https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd
wget https://medium.com/javascript-scene/how-to-use-es6-for-isomorphic-javascript-apps-2a9c3abe5ea2
wget https://medium.com/javascript-scene/javascript-training-sucks-284b53666245
wget https://medium.com/javascript-scene/jsx-looks-like-an-abomination-1c1ec351a918
wget https://medium.com/javascript-scene/the-two-pillars-of-javascript-ee6f3281e7f3
wget https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4
wget https://medium.com/javascript-scene/what-is-webassembly-the-dawn-of-a-new-era-61256ec5a8f6
wget https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284
wget https://medium.com/sketch-app/harnessing-vector-awesomeness-in-sketch-3c9621408138
wget https://medium.com/the-engineering-team/pragmatic-clean-code-architecture-2a60ff1c9a80
wget https://medium.com/the-year-of-the-looking-glass/average-manager-vs-great-manager-cf8a2e30907d
echo "All Done!"
